### ISSUE TITLE
getting error with version 1.1 

### ISSUE THREAD

**Issue by saritaa-nimblechapps** [doordeck/doordeck-sdk-java#13]
using version 1.1 : 
doordeck certification can't generate when I change version name "2.1.0-SNAPSHOT" than work fine and also generate certificate. 
 internal fun createHttpClient() {
        this.client = DoordeckClient.Builder()
            .baseUrl(URI.create(BuildConfig.BASE_URL_API))
            .userAgent(USER_AGENT_PREFIX + BuildConfig.VERSION_NAME)
            .authToken(apiKey)
            .build()
    }

in this calling version name why needs

**Comment by RafaRuiz** [comment]
Hello @saritaa-nimblechapps
There isn't such a `1.1` version.
The one that has been longer online is `1.0.3` and the `1.0.4` has been released a couple of days ago.

Could you please let me know what version you're using and if you could output any more information about the error you're having?
