### ISSUE TITLE
org/gradle/api/plugins/quality/FindBugs issue

### ISSUE THREAD

**Issue by bot101** [doordeck/doordeck-sdk-java#15]
I keep getting this error after installing the sdk, and cannot get the application to build:

```
Build file '/Users/ikennaokafor/Downloads/WebViewGold_for_Android_v6.9/AndroidStudioSourceCode/api/build.gradle' line: 2

A problem occurred evaluating project ':api'.
> org/gradle/api/plugins/quality/FindBugs
```

I have followed the installation instructions but this issue persists.

**Comment by marwan87** [comment]
Hi @bot101 are you initialising the SDK with a JWT?

**Comment by bot101** [comment]
> Hi @bot101 are you initialising the SDK with a JWT?

@marwan87 yes.

**Comment by marwan87** [comment]
Could you look at doordeck.com/developer there you will find a few articles on creating correct JWT, setup etc.
